### ISSUE TITLE
server shows a fine branch as "Unknown"

### ISSUE THREAD

**Issue by rwst** [robertwb/sage-patchbot#49] opened 2014-07-03 06:47 UTC
see http://patchbot.sagemath.org/ticket/16007/ which I would like to test but patchbot won't.

**Comment by fchapoton** [comment] 2015-04-21 08:59
This was also caused by a TAB character in the description

**Comment by fchapoton** [comment] 2015-05-27 19:30
This is a duplicate of #58

**Closed by fchapoton** 2015-05-27 19:30 UTC
